### ISSUE TITLE
dx.data.stocks() throws error on latest build

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-plugins#197]
**Description**

Seems like dx.data.stocks() is broken again

**Steps to reproduce**
1. Build and install the plotly-express plugin into your deephaven-core venv
2. Run deephaven-core
3. Run the following snippet:
```
from deephaven.plot import express as dx

stocks = dx.data.stocks()
```

**Expected results**
3. `stocks` table should appear

**Actual results**

3. Error is outputted:
```
r-Scheduler-Serial-1 | .c.ConsoleServiceGrpcImpl | Error running script: java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'deephaven.dherror.DHError'>
Value: table update operation failed. : java.lang.RuntimeException: Error in Python interpreter:
Traceback (most recent call last):
  File "/home/bender/dev/deephaven/iris-oss/core/main/.venv/lib/python3.10/site-packages/deephaven/table.py", line 757, in update
    return Table(j_table=self.j_table.update(*formulas))
RuntimeError: io.deephaven.engine.table.impl.select.FormulaEvaluationException: In formula: random_double = (double) doubleCast(random_gauss.call(i))
	at io.deephaven.temp.c_83b54b00564ac060a55ec1ca8529629e1074601979223f8c5e0e8b1a5cc74d49v55_0.Formula.applyFormulaPerItem(Formula.java:173)
	at io.deephaven.temp.c_83b54b00564ac060a55ec1ca8529629e1074601979223f8c5e0e8b1a5cc74d49v55_0.Formula.lambda$fillChunkHelper$5(Formula.java:162)
	at io.deephaven.engine.rowset.RowSequence.lambda$forAllRowKeys$0(RowSequence.java:175)
	at io.deephaven.engine.rowset.impl.singlerange.SingleRangeMixin.forEachRowKey(SingleRangeMixin.java:17)
	at io.deephaven.engine.rowset.RowSequence.forAllRowKeys(RowSequence.java:174)
	at io.deephaven.temp.c_83b54b00564ac060a55ec1ca8529629e1074601979223f8c5e0e8b1a5cc74d49v55_0.Formula.fillChunkHelper(Formula.java:159)
	at io.deephaven.temp.c_83b54b00564ac060a55ec1ca8529629e1074601979223f8c5e0e8b1a5cc74d49v55_0.Formula.fillChunk(Formula.java:131)
	at io.deephaven.engine.table.impl.sources.ViewColumnSource.fillChunk(ViewColumnSource.java:219)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.doApplyUpdate(SelectColumnLayer.java:412)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.lambda$doSerialApplyUpdate$2(SelectColumnLayer.java:264)
	at io.deephaven.engine.util.systemicmarking.SystemicObjectTracker.executeSystemically(SystemicObjectTracker.java:56)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.doSerialApplyUpdate(SelectColumnLayer.java:263)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer$1.lambda$onAllRequiredColumnsCompleted$1(SelectColumnLayer.java:212)
	at io.deephaven.engine.table.impl.util.ImmediateJobScheduler.submit(ImmediateJobScheduler.java:23)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer$1.onAllRequiredColumnsCompleted(SelectColumnLayer.java:210)
	at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer$SelectLayerCompletionHandler.onLayerCompleted(SelectAndViewAnalyzer.java:627)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.doSerialApplyUpdate(SelectColumnLayer.java:271)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer$1.lambda$onAllRequiredColumnsCompleted$1(SelectColumnLayer.java:212)
	at io.deephaven.engine.table.impl.util.ImmediateJobScheduler.submit(ImmediateJobScheduler.java:23)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer$1.onAllRequiredColumnsCompleted(SelectColumnLayer.java:210)
	at io.deephaven.engine.table.impl.select.analyzers.SelectAndViewAnalyzer$SelectLayerCompletionHandler.onLayerCompleted(SelectAndViewAnalyzer.java:627)
	at io.deephaven.engine.table.impl.select.analyzers.BaseLayer.applyUpdate(BaseLayer.java:76)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.applyUpdate(SelectColumnLayer.java:151)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.applyUpdate(SelectColumnLayer.java:151)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.applyUpdate(SelectColumnLayer.java:151)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.applyUpdate(SelectColumnLayer.java:151)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.applyUpdate(SelectColumnLayer.java:151)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.applyUpdate(SelectColumnLayer.java:151)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.applyUpdate(SelectColumnLayer.java:151)
	at io.deephaven.engine.table.impl.select.analyzers.SelectColumnLayer.applyUpdate(SelectColumnLayer.java:151)
	at io.deephaven.engine.table.impl.QueryTable.lambda$selectOrUpdate$30(QueryTable.java:1500)
	at io.deephaven.engine.table.impl.perf.QueryPerformanceRecorder.withNugget(QueryPerformanceRecorder.java:369)
	at io.deephaven.engine.table.impl.QueryTable.lambda$selectOrUpdate$31(QueryTable.java:1450)
	at io.deephaven.engine.table.impl.QueryTable.memoizeResult(QueryTable.java:3445)
	at io.deephaven.engine.table.impl.QueryTable.selectOrUpdate(QueryTable.java:1449)
	at io.deephaven.engine.table.impl.QueryTable.update(QueryTable.java:1427)
	at io.deephaven.engine.table.impl.QueryTable.update(QueryTable.java:106)
	at io.deephaven.api.TableOperationsDefaults.update(TableOperationsDefaults.java:94)
	at org.jpy.PyLib.executeCode(Native Method)
	at org.jpy.PyObject.executeCode(PyObject.java:138)
	at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:73)
	at io.deephaven.integrations.python.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:221)
	at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:51)
	at io.deephaven.integrations.python.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:221)
	at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$0(AbstractScriptSession.java:150)
	at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:180)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:191)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:179)
	at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:150)
	at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:84)
	at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:102)
	at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$4(ConsoleServiceGrpcImpl.java:186)
	at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$3(SessionState.java:1499)
	at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:1008)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.deephaven.server.runner.scheduler.SchedulerModule$ThreadFactory.lambda$newThread$0(SchedulerModule.java:97)
	at java.base/java.lang.Thread.run(Thread.java:829)
caused by java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'TypeError'>
Value: issubclass() arg 1 must be a class
Line: 246
Namespace: _is_from_np_type
File: /home/bender/dev/deephaven/iris-oss/core/main/.venv/lib/python3.10/site-packages/deephaven/_udf.py
Traceback (most recent call last):
  File "/home/bender/dev/deephaven/iris-oss/core/main/.venv/lib/python3.10/site-packages/deephaven/_udf.py", line 365, in wrapper
  File "/home/bender/dev/deephaven/iris-oss/core/main/.venv/lib/python3.10/site-packages/deephaven/_udf.py", line 334, in _convert_args
  File "/home/bender/dev/deephaven/iris-oss/core/main/.venv/lib/python3.10/site-packages/deephaven/_udf.py", line 334, in <listcomp>
  File "/home/bender/dev/deephaven/iris-oss/core/main/.venv/lib/python3.10/site-packages/deephaven/_udf.py", line 291, in _convert_arg
  File "/home/bender/dev/deephaven/iris-oss/core/main/.venv/lib/python3.10/site-packages/deephaven/_udf.py", line 246, in _is_from_np_type

	at org.jpy.PyLib.callAndReturnObject(Native Method)
	at org.jpy.PyObject.callMethod(PyObject.java:432)
	at io.deephaven.engine.util.PyCallableWrapperJpyImpl.call(PyCallableWrapperJpyImpl.java:209)
	at io.deephaven.temp.c_83b54b00564ac060a55ec1ca8529629e1074601979223f8c5e0e8b1a5cc74d49v55_0.Formula.applyFormulaPerItem(Formula.java:171)
	... 59 more


Line: 759
Namespace: update
File: /home/bender/dev/deephaven/iris-oss/core/main/.venv/lib/python3.10/site-packages/deephaven/table.py
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/home/bender/dev/deephaven/iris-oss/core/main/.venv/lib/python3.10/site-packages/deephaven/plot/express/data/data_generators.py", line 201, in stocks
  File "/home/bender/dev/deephaven/iris-oss/core/main/.venv/lib/python3.10/site-packages/deephaven/table.py", line 759, in update

	at org.jpy.PyLib.executeCode(Native Method)
	at org.jpy.PyObject.executeCode(PyObject.java:138)
	at io.deephaven.engine.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:73)
	at io.deephaven.integrations.python.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:221)
	at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:51)
	at io.deephaven.integrations.python.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:221)
	at io.deephaven.engine.util.AbstractScriptSession.lambda$evaluateScript$0(AbstractScriptSession.java:150)
	at io.deephaven.engine.context.ExecutionContext.lambda$apply$0(ExecutionContext.java:180)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:191)
	at io.deephaven.engine.context.ExecutionContext.apply(ExecutionContext.java:179)
	at io.deephaven.engine.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:150)
	at io.deephaven.engine.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:84)
	at io.deephaven.engine.util.ScriptSession.evaluateScript(ScriptSession.java:102)
	at io.deephaven.server.console.ConsoleServiceGrpcImpl.lambda$executeCommand$4(ConsoleServiceGrpcImpl.java:186)
	at io.deephaven.server.session.SessionState$ExportBuilder.lambda$submit$3(SessionState.java:1499)
	at io.deephaven.server.session.SessionState$ExportObject.doExport(SessionState.java:1008)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.deephaven.server.runner.scheduler.SchedulerModule$ThreadFactory.lambda$newThread$0(SchedulerModule.java:97)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Versions**

Core SHA: 3229d7194916c1614c0cfd5e01f76bf11c9671a3
Engine Version: 0.32.0-SNAPSHOT
Web UI Version: 0.58.0
Java Version: 11.0.21
Barrage Version: 0.6.0

**Comment by dsmmcken** [comment]
```
# it only works if you disable the __future__ import
from __future__ import annotations

from deephaven import empty_table
def iris(size: int = 1) -> Table:
    #or without the type hints
    # def generate_value(a, b, c):
    def generate_value(a:int, b:int, c:str)->str:
        return str(a + b) + c
    static_table = (
        empty_table(size)
        .update(
            [
                "x = i % 3",
                "y = `abc`",
                "z = generate_value(i, x, y)",
            ]
        )
    )
    return static_table

t = iris()
```

It seems I can either not type hint the function or not import __future. Not sure if this is expected.

Filed a ticket in core: https://github.com/deephaven/deephaven-core/issues/5019

**Comment by dsmmcken** [comment]
Fixed in core.
