### ISSUE TITLE
Rollup seems to be failing in dh.ui -- Has for a few releases now

### ISSUE THREAD

**Issue by pete-petey** [deephaven/deephaven-plugins#420]
**Description**

Some versions ago rollups worked.  Now I get errors.  I was told it might be better in this release, but given it's failing in 0.12.0 I thought best to make a ticket.

**Steps to reproduce**

The code is from your examples:
```

import deephaven.ui as ui
from deephaven.ui import use_memo, use_state
from deephaven import agg
import deephaven.plot.express as dx

# import deephaven.plot.express as dx
# stocks = dx.data.stocks()


def get_by_filter(**byargs):
    """
    Gets a by filter where the arguments are all args passed in where the value is true.
    e.g.
    get_by_filter(sym=True, exchange=False) == ["sym"]
    get_by_filter(exchange=False) == []
    get_by_filter(sym=True, exchange=True) == ["sym", "exchange"]

    """
    return [k for k in byargs if byargs[k]]


@ui.component
def stock_table(source):
    is_sym, set_is_sym = ui.use_state(False)
    is_exchange, set_is_exchange = ui.use_state(False)
    highlight, set_highlight = ui.use_state("")
    aggs, set_aggs = ui.use_state(agg.avg(cols=["size", "price", "dollars"]))

    by = get_by_filter(sym=is_sym, exchange=is_exchange)

    formatted_table = ui.use_memo(
        lambda: source.format_row_where(f"sym=`{highlight}`", "LEMONCHIFFON"),
        [source, highlight],
    )
    rolled_table = ui.use_memo(
        lambda: (
            formatted_table
            if len(by) == 0
            else formatted_table.rollup(aggs=aggs, by=by)
        ),
        [formatted_table, aggs, by],
    )

    return ui.flex(
        ui.flex(
            ui.toggle_button(ui.icon("vsSymbolMisc"), "By Sym", on_change=set_is_sym),
            ui.toggle_button(
                ui.icon("vsBell"), "By Exchange", on_change=set_is_exchange
            ),
            (
                ui.fragment(
                    ui.text_field(
                        label="Highlight Sym",
                        label_position="side",
                        value=highlight,
                        on_change=set_highlight,
                    ),
                    ui.contextual_help(
                        ui.heading("Highlight Sym"),
                        ui.content("Enter a sym you would like highlighted."),
                    ),
                )
                if not is_sym and not is_exchange
                else None
            ),
            align_items="center",
            gap="size-100",
            margin="size-100",
            margin_bottom="0",
        ),
        rolled_table,
        direction="column",
        flex_grow=1,
    )


st = stock_table(stocks)
```

**Actual results**

The error:
```Error rendering __main__.stock_table
Traceback (most recent call last):
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/ui/object_types/ElementMessageStream.py", line 157, in _render
    node = self._renderer.render(self._element)
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/ui/renderer/Renderer.py", line 111, in render
    return _render_element(element, self._context)
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/ui/renderer/Renderer.py", line 84, in _render_element
    props = element.render(context)
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/ui/elements/FunctionElement.py", line 37, in render
    children = self._render()
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/ui/components/make_component.py", line 23, in <lambda>
    return FunctionElement(component_type, lambda: func(*args, **kwargs))
  File "<string>", line 56, in stock_table
TypeError: toggle_button() got an unexpected keyword argument 'on_change'
toggle_button() got an unexpected keyword argument 'on_change'
Traceback (most recent call last):
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/ui/object_types/ElementMessageStream.py", line 183, in _process_callable_queue
    self._render()
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/ui/object_types/ElementMessageStream.py", line 162, in _render
    raise e
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/ui/object_types/ElementMessageStream.py", line 157, in _render
    node = self._renderer.render(self._element)
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/ui/renderer/Renderer.py", line 111, in render
    return _render_element(element, self._context)
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/ui/renderer/Renderer.py", line 84, in _render_element
    props = element.render(context)
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/ui/elements/FunctionElement.py", line 37, in render
    children = self._render()
  File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/ui/components/make_component.py", line 23, in <lambda>
    return FunctionElement(component_type, lambda: func(*args, **kwargs))
  File "<string>", line 56, in stock_table
TypeError: toggle_button() got an unexpected keyword argument 'on_change'
```

**Versions**

 - Engine Version: 0.34.0
 - Web UI Version: ...
 - Java Version: ...
 - Barrage Version: ...
 - OS: ...
 - Browser: ...
 - Docker: ...

**Comment by mattrunyon** [comment]
`toggle_button.on_change` is missing from https://github.com/deephaven/deephaven-plugins/pull/402 which results in the error. We should pass through all unknown keyword args in case we missed any or spectrum adds some and we don't update all the components immediately
