### ISSUE TITLE
Could not resolve 'sourceId' 'dashboard'

### ISSUE THREAD

**Issue by bmingles** [deephaven/deephaven-plugins#524]
Every time I start a server from plugins repo and connect a web ui, I see dev tools console error:

```log
Error: Could not resolve 'sourceId': no variable exists with name 'dashboard'
    at Object.onEnd (dh-internal.js:1:856016)
    at dh-internal.js:1:55814
    at dh-internal.js:1:42802
    at Array.forEach (<anonymous>)
    at e.rawOnEnd (dh-internal.js:1:42764)
    at e.onTransportEnd (dh-internal.js:1:42471)
    at Object.$onMessage (dh-core.js:21092:35)
    at MultiplexedWebsocketTransport$3methodref$onMessage$Type.handleEvent_2 [as handleEvent] (dh-core.js:21234:10)
```

I don't have any panels open, so this is unexpected.

**Comment by vbabich** [comment]
https://github.com/deephaven/deephaven-plugins/issues/539
