### ISSUE TITLE
ui.text_area on_key_down throws errors

### ISSUE THREAD

**Issue by mofojed** [deephaven/deephaven-plugins#790]
**Description**

When using an `on_key_down` on `ui.text_area`, it throws errors

**Steps to reproduce**
1. Create a text area using `on_key_down`:  `ta = ui.text_area(on_key_down=print)`
2. Type in the text area

**Expected results**
2. Key down event should get printed to the console

**Actual results**
2. Error is thrown in JS. In the browser console there's an error:
```
VM1166:4866 Uncaught (in promise) Error: Converting circular structure to JSON
    --> starting at object with constructor 'HTMLTextAreaElement'
    |     property '__reactFiber$jftcs3ps5o' -> object with constructor 'FiberNode'
    --- property 'stateNode' closes the circle
    at new JSONRPCErrorException2 (eval at <anonymous> (loadRemoteModule.ts:42:20), <anonymous>:4866:28)
    at JSONRPCClient2.eval (eval at <anonymous> (loadRemoteModule.ts:42:20), <anonymous>:5108:43)
    at step (eval at <anonymous> (loadRemoteModule.ts:42:20), <anonymous>:5015:19)
    at Object.eval [as next] (eval at <anonymous> (loadRemoteModule.ts:42:20), <anonymous>:4962:14)
    at fulfilled (eval at <anonymous> (loadRemoteModule.ts:42:20), <anonymous>:4933:24)
```

**Versions**

Engine Version: 0.37.0-SNAPSHOT
Web UI Version: 0.91.0
Java Version: 11.0.24
Barrage Version: 0.6.0
Browser Name: Chrome 128
OS Name: Linux
matplotlib: 0.0.0
plotly-express: 0.0.0
auth-keycloak: 0.0.0
ui: 0.0.0
example-theme: 0.0.0

**Comment by mofojed** [comment]
@wusteven815 this might be a good one to get back into the flow.
Note we have a `plugin_builder.py` script now, which may be helpful in getting going here: https://github.com/deephaven/deephaven-plugins/?tab=readme-ov-file#using-plugin_builderpy
