### ISSUE TITLE
`deephaven.ui` components can not render tables containing Deephaven vectors

### ISSUE THREAD

**Issue by chipkent** [deephaven/deephaven-plugins#944]
Version: `0.36.1`

Consider this example:
```python
from deephaven import empty_table, ui

table = empty_table(1000).update(["A = i%3", "B = i", "C = A==2"]).group_by(["A"])

@ui.component
def my_panel():
    return ui.stack([ui.panel(table, title="T1"), ui.panel(table, title="T2")])

dashboard = ui.dashboard(my_panel())
```

When using the normal, non-`deephaven.ui` UI, `table` renders fine:
![image](https://github.com/user-attachments/assets/806a1b10-fea2-4642-95ee-d1d9477353a0)

At the same time, the `deephaven.ui` component to display the same table does not render:
![image](https://github.com/user-attachments/assets/a31e8cc4-0f6c-4a8f-9b0f-20a9d63b927e)

The console spits out errors that look like:
```
3dh-internal.js:1 Uncaught Error: java.lang.IllegalStateException: Can't decode column of type io.deephaven.vector.IntVector
    at IllegalStateException_0.createError (dh-core.js:1383:10)
    at IllegalStateException_0.initializeBackingError (dh-core.js:1409:46)
    at IllegalStateException_0.Throwable_0 (dh-core.js:1348:8)
    at IllegalStateException_0.Exception_1 (dh-core.js:1433:18)
    at IllegalStateException_0.RuntimeException_1 (dh-core.js:1446:18)
    at new IllegalStateException_0 (dh-core.js:35032:25)
    at Object.readArrowBuffer (dh-core.js:15267:32)
    at Object.createSnapshot (dh-core.js:15001:38)
    at Object.$startAndMaybeFlush (dh-core.js:13226:23)
    at Object.$apply_1 (dh-core.js:13215:11)
    at Function.apply_47 (dh-core.js:13244:9)
    at lambda (dh-core.js:174:22)
    at dh-internal.js:1:346879
    at Array.forEach (<anonymous>)
    at onMessage (dh-internal.js:1:346858)
    at dh-internal.js:1:43529
    at Array.forEach (<anonymous>)
    at e.rawOnMessage (dh-internal.js:1:43491)
    at dh-internal.js:1:41304
    at Array.forEach (<anonymous>)
    at e.onTransportChunk (dh-internal.js:1:41179)
    at dh-internal.js:1:48107
```

**Comment by mofojed** [comment]
Closing in favour of #701
